#!/usr/bin/env bash

secrets_image_file=image-secrets
secrets_image_size=100MiB
luks_name=luks-$secrets_image_file

function make
{
    set -x

    rm -f $secrets_image_file 2>/dev/null
    fallocate -l $secrets_image_size $secrets_image_file

    sudo losetup -f $secrets_image_file
    local loop_device=$(losetup -j $secrets_image_file | awk -F: '{print $1}')

    sudo dd if=/dev/urandom of=$loop_device status=progress ; sync
    sudo sgdisk -o -n=1 -t=1:8309 -c=1:"Linux LUKS" $loop_device
    sudo partprobe $loop_device

    local partition="${loop_device}p1"
    sudo cryptsetup luksFormat $partition
    sudo cryptsetup open $partition $luks_name

    local mapper_device=/dev/mapper/$luks_name
    sudo mkfs.vfat $mapper_device

    local this_user=$(whoami)
    sudo mount -o uid=$this_user,gid=$this_user $mapper_device /mnt

    rsync -av --exclude=.gitkeep payload /mnt

    sudo umount $mapper_device
    sudo cryptsetup close $luks_name
    sudo losetup -d $loop_device

    set +x

    if [[ -r $secrets_image_file ]]; then
        echo created \'$secrets_image_file\'
        echo ready to \'dd\' to a thumb drive, for example:
        echo sudo dd if=$secrets_image_file of=\<your-device\> status=progress \; sudo sync
    fi
}

# -----------------------------------------------------------------------------

make
